const ListDrug = {
    list:[
        {
            name:'非处方药',
        },
        {
            name:'处方药',
        },
        {
            name:'中药',
        },
        {
            name:'医疗器械',
        },
        {
            name:'个人护理品',
        },
        {
            name:'保健品',
        },
        {
            name:'食品',
        },
        {
            name:'生活便利品',
        },
    ],
    list1:[
        [
            {
                img:'',
                name:'儿童用药',
                url:"",
            },
            {
                img:'',
                name:'妇科用药',
                url:"",
            },
            {
                img:'',
                name:'感冒用药',
                url:"",
            },
            {
                img:'',
                name:'清热解毒用药',
                url:"",
            },
            {
                img:'',
                name:'呼吸系统用药',
                url:"",
            },
            {
                img:'',
                name:'解热镇痛消炎',
                url:"",
            },
            {
                img:'',
                name:'骨伤科用药',
                url:"",
            },
            {
                img:'',
                name:'消化系统用药',
                url:"",
            }, 
        ],
        [
            {
                img:'',
                name:'维生素矿物质',
                url:"",
            },
            {
                img:'',
                name:'五官用药',
                url:"",
            },
            {
                img:'',
                name:'外用药',
                url:"",
            },
            {
                img:'',
                name:'滋补养颜',
                url:"",
            },
            {
                img:'',
                name:'神经系统用药',
                url:"",
            },
            {
                img:'',
                name:'抗过敏眩晕',
                url:"",
            },
            {
                img:'',
                name:'内分泌用药',
                url:"",
            },
            {
                img:'',
                name:'循环系统用药',
                url:"",
            },        
        ],
        [
            {
                img:'',
                name:'其他',
                url:"",
            },
            {
                img:'',
                name:'肝胆用药',
                url:"",
            },
        ]
    ],
    list2:[
        [
            {
                img:'',
                name:'儿童用药',
                url:"",
            },
            {
                img:'',
                name:'肝胆用药',
                url:"",
            },
            {
                img:'',
                name:'骨伤科用药',
                url:"",
            },
            {
                img:'',
                name:'解热镇痛消炎',
                url:"",
            },
            {
                img:'',
                name:'妇科用药',
                url:"",
            },
            {
                img:'',
                name:'感冒用药',
                url:"",
            },
            {
                img:'',
                name:'呼吸系统用药',
                url:"",
            },
            {
                img:'',
                name:'抗感染用药',
                url:"",
            }, 
        ],
        [
            {
                img:'',
                name:'泌尿生殖用药',
                url:"",
            },
            {
                img:'',
                name:'计划生育用药',
                url:"",
            },
            {
                img:'',
                name:'神经系统用药',
                url:"",
            },
            {
                img:'',
                name:'维生素矿物质',
                url:"",
            },
            {
                img:'',
                name:'内分泌用药',
                url:"",
            },
            {
                img:'',
                name:'清热解毒用药',
                url:"",
            },
            {
                img:'',
                name:'外用药',
                url:"",
            },
            {
                img:'',
                name:'五官用药',
                url:"",
            },        
        ],
        [
            {
                img:'',
                name:'消化系统用药',
                url:"",
            },
            {
                img:'',
                name:'滋补养颜',
                url:"",
            },
            {
                img:'',
                name:'抗过敏眩晕',
                url:"",
            },
            {
                img:'',
                name:'心脑血管用药',
                url:"",
            },
            {
                img:'',
                name:'皮肤科用药',
                url:"",
            },
            {
                img:'',
                name:'其他',
                url:"",
            },
        ]  
    ],
    list3:[
        [
            {
                img:'',
                name:'参茸贵细',
                url:"",
            },
            {
                img:'',
                name:'中药软片',
                url:"",
            },
            {
                img:'',
                name:'药食同源',
                url:"",
            },
        ]
    ],
    list4:[
        [
            {
                img:'',
                name:'成人用品',
                url:"",
            },
            {
                img:'',
                name:'康复理疗',
                url:"",
            },
            {
                img:'',
                name:'家用诊疗',
                url:"",
            },
            {
                img:'',
                name:'医用敷料',
                url:"",
            },
            {
                img:'',
                name:'其他',
                url:"",
            },
        ]
    ],
    list5:[
        [
            {
                img:'',
                name:'功能性用品',
                url:"",
            },
            {
                img:'',
                name:'浴巾洗护',
                url:"",
            },
            {
                img:'',
                name:'面部护理',
                url:"",
            },
            {
                img:'',
                name:'五官护理',
                url:"",
            },
            {
                img:'',
                name:'其他护理',
                url:"",
            },
        ] 
    ],
    list6:[
        [
            {
                img:'',
                name:'儿童保健食品',
                url:"",
            },
            {
                img:'',
                name:'美容抗衰老抗氧化',
                url:"",
            },
            {
                img:'',
                name:'维生素矿物质',
                url:"",
            },
            {
                img:'',
                name:'改善消化功能',
                url:"",
            },
            {
                img:'',
                name:'免疫调节抗疲劳',
                url:"",
            },
            {
                img:'',
                name:'五官保健食品',
                url:"",
            },
        ]  
    ],
    list7:[
        [
            {
                img:'',
                name:'清热解毒祛湿',
                url:"",
            },
            {
                img:'',
                name:'饮品',
                url:"",
            },
            {
                img:'',
                name:'代用茶/花茶',
                url:"",
            },
            {
                img:'',
                name:'休闲农副食品',
                url:"",
            },
            {
                img:'',
                name:'其他食品',
                url:"",
            },
        ] 
    ],
    list8:[
        [
            {
                img:'',
                name:'家庭清洁用品',
                url:"",
            },
            {
                img:'',
                name:'其他',
                url:"",
            },
        ]
    ],
    listTabs:[
        {
            name:'应季常备',
        },
        {
            name:'家庭保健',
        },
        {
            name:'营养滋补',
        },
        {
            name:'性福生活',
        },
        {
            name:'妇女之友',
        },
        {
            name:'宝宝乐园',
        },
        {
            name:'老当益壮',
        },
        {
            name:'跌打损伤',
        },  
        {
            name:'出行必备',
        },
        {
            name:'瘦身美容',
        },      
    ],

    arr:[
        {
            name:'应季常备',
        },
        {
            name:'家庭保健',
        },
        {
            name:'营养滋补',
        },
        {
            name:'性福生活',
        },
        {
            name:'妇女之友',
        },
        {
            name:'宝宝乐园',
        },
        {
            name:'老当益壮',
        },
        {
            name:'跌打损伤',
        },  
        {
            name:'出行必备',
        },
        {
            name:'瘦身美容',
        }, 
    ]


};



export default ListDrug;