//保存商品数据
export const GETPROUCTION='GETPRODUCTION';
//选择商品
export const TOGGLESELECT='TOGGLESELECT';
//编辑商品
export const EDITPRODUCTION='EDITPRODUCTION';
//清空选择
export const CLEARSELECTED='CLEARSELECTED';